"""Project database ver1_5

Revision ID: 107f78ed2d74
Revises: a0283619aaea
Create Date: 2020-05-09 11:11:06.843867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107f78ed2d74'
down_revision = 'a0283619aaea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('matches_name_key', 'matches', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('matches_name_key', 'matches', ['name'])
    # ### end Alembic commands ###
